const API_BASE = window.location.protocol === 'file:' ? 'http://localhost:8000' : window.location.origin;
const APP = window.APP = { currentSymbol: 'XRPUSDT', currentInterval: '4h', lastData: {}, cacheKey: 'asple-predictor-cache', chart: null, candleSeries: null };
const MODEL_DISPLAY_NAMES = { model_a: 'XGBoost', model_b: 'GRU (PyTorch)', model_c: 'Prophet+XGBoost', model_d: 'TFT (Temporal Fusion)', ensemble: 'Ensemble' };
function getModelName(key) { return MODEL_DISPLAY_NAMES[key] || key; }
const CONDITION_NAMES = { rsi_oversold: 'RSI Sobrevendido', high_volume: 'Volumen Alto', strong_trend: 'Tendencia Fuerte', ranging_market: 'Mercado Lateral', post_macd_cross: 'Cruce MACD' };
const CONDITION_TOOLTIPS = { rsi_oversold: 'RSI < 30: activo posiblemente sobrevendido, propenso a rebote alcista', high_volume: 'Volumen supera el promedio significativamente; movimiento respaldado por fuerza institucional', strong_trend: 'ADX > 25: tendencia definida con momentum sostenido (alcista o bajista)', ranging_market: 'Precio oscila entre soporte y resistencia sin dirección clara; condición ideal para grid trading', post_macd_cross: 'La línea MACD acaba de cruzar la señal; posible cambio de momentum inminente' };
const MODEL_TOOLTIPS = { model_a: 'Gradient Boosting sobre indicadores técnicos. Rápido y eficiente en tendencias claras.', model_b: 'Red neuronal recurrente. Captura patrones temporales en secuencias de velas.', model_c: 'Modelo híbrido: Prophet detecta ciclos y estacionalidad, XGBoost refina la predicción.', model_d: 'Temporal Fusion Transformer. Aprende dependencias temporales y pondera variables relevantes.' };
function formatAccuracy(model) { const accuracy = model.accuracy ?? model.accuracy_30d; const verified = model.verified_count ?? model.verified_predictions ?? 0; return accuracy === null || accuracy === undefined || !verified ? '-' : percent(accuracy); }
function tooltip(content) { return `<span class="tooltip-wrap"><span class="tooltip-icon" tabindex="0">&#9432;</span><span class="tooltip-content">${escapeHtml(content)}</span></span>`; }
function modelHeader(key) { return `${escapeHtml(getModelName(key))} ${tooltip(MODEL_TOOLTIPS[key] || '')}`; }
class ApiClient {
  constructor(baseUrl = API_BASE) { this.baseUrl = baseUrl; }
  async get(path, params = {}) { const url = new URL(this.baseUrl + path); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== '') url.searchParams.set(key, value); }); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10000); try { const response = await fetch(url, { signal: controller.signal }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.json(); } finally { clearTimeout(timer); } }
  status() { return this.get('/'); }
  candles(symbol, interval) { return this.get('/api/candles', { symbol, interval: interval.toLowerCase() }); }
  consensus(symbol, interval) { return this.get('/api/predictions/consensus', { symbol, interval: interval.toLowerCase() }); }
  latest(symbol, interval, limit = 10) { return this.get('/api/predictions/latest', { symbol, interval: interval.toLowerCase(), limit }); }
  history(symbol, model, days = 30) { return this.get('/api/predictions/history', { symbol, model, days }); }
  modelsStatus() { return this.get('/api/models/status'); }
  conditions(model) { return this.get('/api/models/accuracy-by-condition', { model }); }
  grid(params) { return this.get('/api/grid/recommend', params); }
}
const api = new ApiClient();
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '-').replace(/[&<>\'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const percent = (value, digits = 1) => Number.isFinite(Number(value)) ? `${(Number(value) * 100).toFixed(digits)}%` : '-';
const money = (value, digits = 4) => Number.isFinite(Number(value)) ? `$${Number(value).toFixed(digits)}` : '-';
const signalClass = signal => signal === 'ALCISTA' ? 'bullish' : signal === 'BAJISTA' ? 'bearish' : 'neutral';
function cache(data) { APP.lastData = { ...APP.lastData, ...data }; localStorage.setItem(APP.cacheKey, JSON.stringify(APP.lastData)); }
function restoreCache() { try { APP.lastData = JSON.parse(localStorage.getItem(APP.cacheKey) || '{}'); } catch (_) { APP.lastData = {}; } }
function setOffline(offline) { $('#offline-banner').classList.toggle('hidden', !offline); const chip = $('#api-chip'); chip.classList.toggle('online', !offline); chip.classList.toggle('offline', offline); chip.querySelector('span').textContent = offline ? 'API Offline' : 'API Online'; }
async function checkApiStatus() { try { await api.status(); setOffline(false); } catch (_) { setOffline(true); } }
function clearChart() { if (APP.candleSeries) { APP.candleSeries.setData([]); APP.candleSeries = null; } if (APP.chart) { APP.chart.remove(); APP.chart = null; } $('#price-chart').innerHTML = ''; }
function renderModelCards(consensus, status) { const byModel = Object.fromEntries((status?.models || []).map(item => [item.model_name, item])); const definitions = [['model_a', 'model-a'], ['model_b', 'model-b'], ['model_c', 'model-c']]; $('#model-cards').innerHTML = definitions.map(([key, css]) => { const result = consensus[key] || {}; const model = byModel[key] || {}; return `<div class="card model-card ${css}"><div class="model-name"><h3>${getModelName(key)}</h3><span class="accuracy">${percent(model.accuracy_30d)}</span></div><div class="model-meta"><span class="signal ${signalClass(result.signal)}">${escapeHtml(result.signal)}</span><span class="mono muted">${percent(result.probability_up)}</span></div><div class="progress"><i style="width:${Math.max(0, Math.min(100, Number(result.probability_up || 0) * 100))}%"></i></div><div class="features">${(result.top_features || []).slice(0, 3).map(feature => `<span class="feature">${escapeHtml(feature[0])}</span>`).join('')}</div></div>`; }).join(''); }
function renderConsensus(data) { $('#consensus-card').innerHTML = `<div class="eyebrow">CONSENSO ENSEMBLE</div><div class="big-prob">${percent(data.consensus_probability_up, 2)}</div><div class="agreement">${escapeHtml(data.agreement_count)}/3 modelos coinciden</div><div class="signal ${signalClass(data.consensus_signal)}" style="margin-top:13px">${escapeHtml(data.consensus_signal)}</div>`; $('#chart-signal').className = `signal ${signalClass(data.consensus_signal)}`; $('#chart-signal').textContent = data.consensus_signal; }
function renderRecent(rows) { $('#recent-predictions').innerHTML = (rows || []).slice(0, 10).map(row => `<div class="prediction-row"><span><b>${escapeHtml(row.symbol)}</b><br><span class="muted">${escapeHtml(getModelName(row.model_name))}</span></span><span class="signal ${signalClass(row.signal)}">${escapeHtml(row.signal)}</span><span class="prob">${percent(row.probability_up)}</span><span class="${row.is_verified ? 'verified' : 'pending'}">${row.is_verified ? (row.was_correct ? 'OK' : 'X') : '...'}</span></div>`).join('') || '<p class="muted">Sin predicciones registradas.</p>'; }
function renderChart(candles, consensus, interval) { clearChart(); const box = $('#price-chart'); if (!window.LightweightCharts) { box.innerHTML = '<p class="muted">Chart no disponible.</p>'; return; } const isIntraday = ['1h', '4h', '12h'].includes((interval || '4h').toLowerCase()); APP.chart = LightweightCharts.createChart(box, { layout: { background: { color: '#161B22' }, textColor: '#8B949E' }, grid: { vertLines: { color: '#21262D' }, horzLines: { color: '#21262D' } }, rightPriceScale: { borderColor: '#30363D' }, timeScale: { borderColor: '#30363D', timeVisible: isIntraday, secondsVisible: false } }); APP.candleSeries = APP.chart.addCandlestickSeries({ upColor: '#3FB950', downColor: '#F85149', borderVisible: false, wickUpColor: '#3FB950', wickDownColor: '#F85149' }); if (candles.length) { APP.candleSeries.setData(candles); const last = candles[candles.length - 1]; APP.candleSeries.setMarkers([{ time: last.time, position: consensus.consensus_signal === 'ALCISTA' ? 'belowBar' : 'aboveBar', color: consensus.consensus_signal === 'ALCISTA' ? '#3FB950' : '#F85149', shape: consensus.consensus_signal === 'ALCISTA' ? 'arrowUp' : 'arrowDown', text: consensus.consensus_signal }]); APP.chart.timeScale().fitContent(); APP.chart.timeScale().scrollToRealTime(); } }
async function loadDashboard() { const symbol = $('#dashboard-symbol').value; const interval = $('#dashboard-interval').value.toLowerCase(); APP.currentSymbol = symbol; APP.currentInterval = interval; clearChart(); try { const [candles, consensus, rows, status] = await Promise.all([api.candles(symbol, interval), api.consensus(symbol, interval), api.latest(symbol, interval, 10), api.modelsStatus()]); cache({ candles, consensus, rows, status }); renderModelCards(consensus, status); renderConsensus(consensus); renderRecent(rows); renderChart(candles, consensus, interval); if (consensus.indicators) { $('#indicator-rsi').textContent = Number(consensus.indicators.rsi_14).toFixed(2); $('#indicator-macd').textContent = Number(consensus.indicators.macd).toFixed(5); $('#indicator-atr').textContent = Number(consensus.indicators.atr_14).toFixed(5); } $('#dashboard-updated').textContent = `Actualizado ${new Date().toLocaleTimeString()}`; $('#chart-caption').textContent = `${symbol} - ${interval.toUpperCase()} - consenso en vivo`; setOffline(false); } catch (_) { setOffline(true); if (APP.lastData.consensus) { renderModelCards(APP.lastData.consensus, APP.lastData.status); renderConsensus(APP.lastData.consensus); renderRecent(APP.lastData.rows); renderChart(APP.lastData.candles || [], APP.lastData.consensus, APP.currentInterval); } } }
async function refreshDashboard() { const button = $('#refresh-dashboard'); const original = button.textContent; button.disabled = true; button.textContent = 'Actualizando...'; try { await loadDashboard(); } finally { button.disabled = false; button.textContent = original; } }
function renderBattle(status, conditionSets, history) { const models = status.models || []; const scores = models.map(model => { const verified = model.verified_count ?? model.verified_predictions ?? 0; return `<div class="card score-card"><h3>${modelHeader(model.model_name)}</h3><strong>${formatAccuracy(model)}</strong><p class="muted">${model.total_predictions || 0} predicciones<br><small>${verified} de ${model.total_predictions || 0} verificadas</small></p></div>`; }).join(''); const conditions = ['rsi_oversold', 'high_volume', 'strong_trend', 'ranging_market', 'post_macd_cross']; const lookup = Object.fromEntries(Object.entries(conditionSets).flatMap(([model, rows]) => rows.map(row => [`${row.condition_name}:${model}`, row]))); const conditionRows = conditions.map(condition => { const entries = models.map(model => lookup[`${condition}:${model.model_name}`] || {}); const values = entries.map(entry => entry.accuracy); const best = Math.max(...values.map(value => Number(value ?? -1))); const label = `<span class="condition-label">${escapeHtml(CONDITION_NAMES[condition] || condition)} ${tooltip(CONDITION_TOOLTIPS[condition] || '')}</span>`; return `<tr><td>${label}</td>${entries.map(entry => { const verified = entry.verified_count ?? entry.verified_predictions ?? 0; return `<td class="${entry.accuracy !== null && entry.accuracy !== undefined && entry.accuracy === best ? 'winner' : ''}">${entry.accuracy === null || entry.accuracy === undefined || !verified ? '-' : percent(entry.accuracy)}<small class="condition-count">${verified} de ${entry.total_predictions || 0} verificadas</small></td>`; }).join('')}</tr>`; }).join(''); const historyRows = (history || []).slice(0, 30).map(row => `<tr><td>${escapeHtml(new Date(row.predicted_at).toLocaleString())}</td><td>${escapeHtml(row.symbol)}</td><td>${escapeHtml(getModelName(row.model_name))}</td><td><span class="signal ${signalClass(row.signal)}">${escapeHtml(row.signal)}</span></td><td class="mono">${percent(row.probability_up)}</td><td>${row.is_verified ? (row.was_correct ? 'ACERTO' : 'FALLO') : 'PENDIENTE'}</td><td class="muted">${escapeHtml((row.was_correct ? row.why_correct : row.why_wrong || '').slice(0, 60))}</td></tr>`).join(''); $('#battle-content').innerHTML = `<div class="battle-grid">${scores}</div><div class="card table-card"><table class="data-table"><thead><tr><th>Condicion</th>${models.map(model => `<th>${modelHeader(model.model_name)}</th>`).join('')}</tr></thead><tbody>${conditionRows}</tbody></table></div><div class="card table-card"><table class="data-table"><thead><tr><th>Fecha</th><th>Simbolo</th><th>Modelo</th><th>Senal</th><th>Prob.</th><th>Resultado</th><th>Detalle</th></tr></thead><tbody>${historyRows || '<tr><td colspan="7">Sin historial.</td></tr>'}</tbody></table></div>`; }
async function loadBattle() { try { const status = await api.modelsStatus(); const names = ['model_a', 'model_b', 'model_c', 'model_d', 'ensemble']; const conditionRows = await Promise.all(names.map(name => api.conditions(name))); const history = await api.history(null, null, 30); renderBattle(status, Object.fromEntries(names.map((name, index) => [name, conditionRows[index]])), history); setOffline(false); } catch (_) { setOffline(true); } }
function gridSvg(data) { const floor = Number(data.recommended_floor), ceiling = Number(data.recommended_ceiling), current = Number(data.current_price), count = Number(data.suggested_grids), y = value => 170 - ((value - floor) / (ceiling - floor)) * 140; let lines = ''; for (let index = 0; index <= count; index++) { const value = floor + (ceiling - floor) * index / count; lines += `<line x1="30" x2="570" y1="${y(value)}" y2="${y(value)}" stroke="#30363D"/>`; } return `<svg class="grid-svg" viewBox="0 0 620 190"><line x1="30" x2="570" y1="${y(floor)}" y2="${y(floor)}" stroke="#3FB950" stroke-width="2"/><line x1="30" x2="570" y1="${y(ceiling)}" y2="${y(ceiling)}" stroke="#F85149" stroke-width="2"/>${lines}<circle cx="300" cy="${y(current)}" r="5" fill="#2F81F7"/></svg>`; }
function renderGrid(data) { const analysis = data.analysis, prediction = data.prediction_signal; $('#grid-result').className = 'grid-result card'; $('#grid-result').innerHTML = `<div class="grid-header"><div><p class="eyebrow">RECOMENDACION ${escapeHtml(data.symbol)}</p><div class="price-large">${money(data.current_price)}</div><span class="muted">Rango ${Number(data.range_pct).toFixed(2)}%</span></div><span class="signal ${signalClass(prediction.consensus_signal)}">${escapeHtml(prediction.consensus_signal)}</span></div><div class="level-row"><div class="level floor"><span>Piso recomendado</span><strong>${money(data.recommended_floor)}</strong></div><div class="level ceiling"><span>Techo recomendado</span><strong>${money(data.recommended_ceiling)}</strong></div></div>${gridSvg(data)}<div class="card-title"><h2>Configuracion sugerida</h2><button id="copy-grid" class="button secondary">Copiar configuracion</button></div><div class="indicator-strip"><div><span>GRIDS</span><b>${data.suggested_grids}</b></div><div><span>ESPACIADO</span><b>${Number(data.spacing_pct).toFixed(2)}%</b></div><div><span>CAPITAL / GRID</span><b>${money(data.capital_per_grid, 2)}</b></div></div><h2 style="font-size:14px;margin-top:24px">Por que estos niveles</h2><div class="why">Soporte: <b>${money(analysis.main_support)}</b> (${analysis.support_touches} toques) - Resistencia: <b>${money(analysis.main_resistance)}</b> (${analysis.resistance_touches} toques) - ATR: <b>${money(analysis.atr)}</b></div><p class="disclaimer">${escapeHtml(data.disclaimer)}</p>`; $('#copy-grid').onclick = () => { const text = `ASPLE Trade - Grid ${data.symbol.replace('USDT', '/USDT')}\nPiso: ${money(data.recommended_floor)} | Techo: ${money(data.recommended_ceiling)}\nGrids: ${data.suggested_grids} | Capital/grid: ${money(data.capital_per_grid, 2)}\nGenerado: ${new Date().toLocaleString()}`; navigator.clipboard.writeText(text).then(() => { const toast = $('#toast'); toast.textContent = 'Configuracion copiada'; toast.classList.remove('hidden'); setTimeout(() => toast.classList.add('hidden'), 2200); }); }; }
async function loadGrid(event) { event.preventDefault(); const params = { symbol: $('#grid-symbol').value, capital: $('#grid-capital').value, risk: $('#grid-risk').value, days: $('#grid-days').value }; const button = event.target.querySelector('button'); button.disabled = true; button.textContent = 'ANALIZANDO...'; try { const data = await api.grid(params); cache({ grid: data }); renderGrid(data); setOffline(false); } catch (_) { setOffline(true); $('#grid-result').innerHTML = '<div class="empty-state"><h2>No fue posible analizar</h2><p class="muted">Comprueba que la API este activa y Binance sea accesible.</p></div>'; } finally { button.disabled = false; button.innerHTML = 'ANALIZAR <span>-&gt;</span>'; } }
function route() { const name = (location.hash || '#dashboard').slice(1); ['dashboard', 'battle', 'grid'].forEach(screen => { $(`#screen-${screen}`).classList.toggle('hidden', screen !== name); document.querySelector(`[data-route="${screen}"]`).classList.toggle('active', screen === name); }); if (name === 'dashboard') loadDashboard(); if (name === 'battle') loadBattle(); }
document.addEventListener('DOMContentLoaded', () => { restoreCache(); $('#grid-form').addEventListener('submit', loadGrid); $('#dashboard-symbol').addEventListener('change', loadDashboard); $('#dashboard-interval').addEventListener('change', loadDashboard); $('#refresh-dashboard').addEventListener('click', refreshDashboard); window.addEventListener('hashchange', route); route(); checkApiStatus(); setInterval(checkApiStatus, 30000); setInterval(() => { if ((location.hash || '#dashboard') === '#dashboard') loadDashboard(); }, 60000); });
// Optional Model D card: the existing dashboard renderer remains compatible with 3 models.
const _loadDashboardWithOptionalTft = loadDashboard;
loadDashboard = async function () {
  await _loadDashboardWithOptionalTft();
  const consensus = APP.lastData.consensus;
  const status = APP.lastData.status;
  if (consensus?.model_d && status?.models?.some(model => model.model_name === 'model_d') && !document.querySelector('#model-cards .model-d')) {
    const result = consensus.model_d;
    const model = status.models.find(item => item.model_name === 'model_d') || {};
    $('#model-cards').insertAdjacentHTML('beforeend', `<div class="card model-card model-d"><div class="model-name"><h3>${getModelName('model_d')}</h3><span class="accuracy">${percent(model.accuracy_30d)}</span></div><div class="model-meta"><span class="signal ${signalClass(result.signal)}">${escapeHtml(result.signal)}</span><span class="mono muted">${percent(result.probability_up)}</span></div><div class="progress"><i style="width:${Math.max(0, Math.min(100, Number(result.probability_up || 0) * 100))}%"></i></div></div>`);
  }
};
